### ISSUE TITLE
Badges don't always load when PR first loaded

### ISSUE THREAD

**Issue by NeonWizard** [pullrequestbadge/support#1]
When a PR page is loaded for the first time, the badges at the top most of the time don't load, and the page must be refreshed. See the below image.

![image](https://user-images.githubusercontent.com/1355586/111848977-20d0da00-88d2-11eb-8abd-adb49f977f3d.png)

**Comment by stefanbuck** [comment]
Hi, first apologies for the delay. Somehow this notification slipped through. I'm aware of this issue, but so far I didn't spend much time on it, to be really honest. The badges are generated using https://badgen.net and as far as I can tell this service is working as expected. GitHub is using a CDN for all user content and this seems to be the problem when requesting an image from badgent.net for the first time. Maybe the generates takes a few ms too long.
