### ISSUE TITLE
Feature to create a badge from external pipeline

### ISSUE THREAD

**Issue by jgalan** [pullrequestbadge/support#2]
Hi,

it would be easy to create a badge pointing to an external SVG image?

Such as including this one

https://gitlab.cern.ch/rest-for-physics/framework/badges/development/pipeline.svg

[![pipeline status](https://gitlab.cern.ch/rest-for-physics/framework/badges/development/pipeline.svg)](https://gitlab.cern.ch/rest-for-physics/framework/-/commits/development)

`development` is the name of the branch, so I would like that if the pull-request is from `development` it points to the `development` pipeline, of course.

Would be great! It is this possible?

**Comment by stefanbuck** [comment]
Hi, first apologies for the delay. Somehow this notification slipped through. Sound like a use case for the [imageUrl](https://pullrequestbadge.com/#imageUrl) attribute. The configuration for your specific use case should be easy as

```
- imageUrl: "https://gitlab.cern.ch/rest-for-physics/framework/badges/$branchName/pipeline.svg"
```

Please let me know if this solves the problem for you.

**Comment by jgalan** [comment]
Ok, thanks! It works awesome.

https://github.com/rest-for-physics/geant4lib/pull/11

The only issue is the question mark that it appears at the end and that points to your site https://pullrequestbadge.com/?utm_medium=github&utm_source=rest-for-physics&utm_campaign=badge_info

Perhaps you added the question mark intentionally, but it looks as a missing image to me.

===

On the other hand, I have a question you probably now the answer but it is not connected with `pullrequestbaddge`.

It is really cool to be able to use a variable as `$branchName` to point different branch pipeline badges, do you know if this is easy to do also at the README.md level? We use the badge there.

https://github.com/rest-for-physics/geant4lib/blob/master/README.md

But it always points to master even if we change the branch at github.

**Comment by stefanbuck** [comment]
Thanks for your feedback on the question mark. It's my attempt to spread the word about existence of pull request badge. I thought such a small icon is better than "power by..." but I see your point. If you have any suggestion please let me know.

Regarding the other question, I'm afraid there is no solution, besides modifying the readme for each branch (which doesn't scale very well). That said, you could write a GitHub Action that does that modification for you, but not sure if this is worth the effort.

**Comment by jgalan** [comment]
Yes, you should replace the question mark, to make it simple perhaps you could use the small icon looking as a pill, dark-gray and purple. And perhaps adding a PR and/or a small storm lightning inside the icon.
