### ISSUE TITLE
Creating a badge fulfilling 2 conditions

### ISSUE THREAD

**Issue by jgalan** [pullrequestbadge/support#3]
Hi I am trying a badge that appears when 2 conditions are fulfilled.

I did the following tries, but non of them seemed to work properly:

```
- label: "PR Size"
  message: "Medium: $additions"
  color: "orange"
  when: "$additions > 99"
  when: "$additions < 201"
```

or 

```
- label: "PR Size"
  message: "Medium: $additions"
  color: "orange"
  when: "$additions > 99 and $additions < 201"
```

**Comment by stefanbuck** [comment]
This should do the trick. 

```
- label: "PR Size"
  message: "Medium: $additions"
  color: "orange"
  when: "$additions > 99 && $additions < 201"
```

**Comment by bcngb** [comment]
> Hi I am trying a badge that appears when 2 conditions are fulfilled.
> 
> I did the following tries, but non of them seemed to work properly:
> 
> ```
> - label: "PR Size"
>   message: "Medium: $additions"
>   color: "orange"
>   when: "$additions > 99"
>   when: "$additions < 201"
> ```
> 
> or
> 
> ```
> - label: "PR Size"
>   message: "Medium: $additions"
>   color: "orange"
>   when: "$additions > 99 and $additions < 201"
> ```
